#include <stdio.h>
/**
* main - Entry point function name
* Description: Each new term in the
* Fibonacci sequence is generated by
* adding the previous two terms. By
* starting with 1 and 2, the first 10
* terms will be: 1, 2, 3, 5, 8, 13, 21,
* 34, 55, 89. By considering the terms
* in the Fibonacci sequence whose values
* do not exceed 4,000,000, write a program
* that finds and prints the sum of the
* even-valued terms, followed by a new line.
* Return: Success (0)
*/
int main(void)
{
	long int prev, sum, current, main_sum;

	sum = 0;
	current = 1;
	prev = 0;
	main_sum = 0;

	while (current <= 4000000)
	{
		prev = current;
		current += sum;
		sum = prev;

		if (current % 2 == 0)
		{
			main_sum += current;
		}
	}
	printf("%ld\n", main_sum);
	return (0);
}
